apiVersion: v1
kind: ConfigMap
metadata:
  name: gitguard-consumer-config
data:
  config.yaml: |
    kafka:
      brokers: {{ toYaml .Values.config.kafka.brokers | nindent 8 }}

    postgres:
      addr: "{{ .Values.config.postgres.addr }}"
      user: "{{ .Values.config.postgres.user }}"
      password: "{{ .Values.config.postgres.password }}"
      dbname: "{{ .Values.config.postgres.dbname }}"

    pagerduty:
      enabled: {{ .Values.config.pagerduty.enabled }}

    slack:
      enabled: {{ .Values.config.slack.enabled }}
      channel_id: {{ .Values.config.slack.channel_id | quote }}

    rules:
{{ toYaml .Values.config.rules | indent 6 }}
